src/ProtoBuf/Builder.js

see: https://github.com/dcodeIO/ProtoBuf.js/issues/219

Handle repeated imports when loading protofiles with a root.

---

src/ProtoBuf/Builder/Message.js

- fixes #279 
I'm guessing I need to do an `npm run build` and commit the dist code too?

add should return this

---

src/ProtoBuf/Builder/Service.js

Allow calling service methods with plain objects

---

externs/ProtoBuf.js

Tested with closure compiler v20150920.

Fix closure annotations

---

src/ProtoBuf/DotProto/Parser.js
tests/suite.js

Resolves https://github.com/dcodeIO/ProtoBuf.js/issues/285#issuecomment-149718823

Parse nested services

---

src/ProtoBuf/Builder/Message.js

Add the noVerify parameter to encodedDelimited.

add noVerify to encodeDelimited

---

cli/pbjs/targets/json.js

Add object to the allowed types for an option

---

cli/targets/proto.js

Am I missing something?
I think that variable "syntax" never is declared in the file.
best regards J

Missing syntax declaration

---

src/field.js

wrong spell role should be rule

wrong spell role should be rule

---

README.md

Fixes #539
in other news, how do you feel about my editor stripping all this whitespace?

Fix to reflection documentation

---

README.md

Solution thanks to http://stackoverflow.com/a/17320389/361684

Fix markdown for pipe in code in table

---

cli/lib/tsd-jsdoc/publish.js

Fix codegen if type name starts with "Object"

---

ext/descriptor/index.js

Handle case where 'extendee' is undefined.

---

cli/targets/static.js

Generate enum TypeScript typings.

---

src/parse.js

Add support for reserved keyword in enums.

---

src/namespace.js

- several errors i run into fairly often where context would be helpful to debug

Extend Error Messages

---

cli/pbts.js

With reference to #1034, this is an example of how extra imports could be added to the generated types using the pbts cli tool.
It's far from an ideal solution, but works.

Custom pbts type imports

---

README.md

After spending a few hours trying to figure out how to connect those 2 great framework, I think it would be a great idea to add that to the doc to save people time in the future. 
Thanks !

Add working rpcImpl with grpc node package

---

package.json

This is used for authentication by wombot.

build: update repository field to point to org

---

index.d.ts
src/root.js

this can be usefull in some scenario, for example fetch from http server with basic auth or custom http header

feat: add configurable Root.prototype.fetch

---

package.json

Based on this comment I think this is the correct URL.
https://github.com/protobufjs/protobuf.js/issues/1210#issuecomment-485744621

fix homepage 404 in npm package

---

package-lock.json

address security warning with elliptic dependency.

deps(security): address elliptic security warning

---

cli/package.json
package-lock.json

If I follow this, glob packages minimatch.  Minimatch released a fix, glob also has a newer build, picking this up should pick up that.
Fixes #1696
Fixes #1697
Fixes #1698

fix(deps): patch minimatch vulnerability

---

.github/workflows/test.yml
cli/package.json
package.json

fix!: drop support for Node 4, 6, 8, 10

---

cli/pbts.js

fix: add import long to the generated .d.ts

---

index.html

fixes #1846
(if gh-pages is the right branch)

docs: toolset diagram image link
