dist/ProtoBuf.js, dist/ProtoBuf.noparse.js, src/ProtoBuf/Builder.js, src/ProtoBuf/DotProto/Parser.js, src/ProtoBuf/Reflect/Service/RPCMethod.js, tests/suite.js
Add the ability to parse streaming requests and responses and expose that information in the reflection API. This is one of the changes needed to support [Protocol Buffers v3](https://github.com/google/protobuf/releases/tag/v3.0.0-alpha-1).
=> Add streaming methods to parser and reflection API

cli/pbjs/targets/json.js, tests/complex.json, tests/complex.proto, tests/suite.js
Adds a field to complex.proto to ensure we can instantiate an object
that includes repeated fields.  Also updates the encoded string checked
in the test but I didn't really verify it against another protobuf
implementation or by hand (though the test does pass).
Fixes #222
=> Makes pb2js handle repeated fields properly.

src/ProtoBuf/Builder/Message.js
Instead of silently dropping bytes fields, `Message#toRaw` should return them as byte sequence objects. `ByteBuffer#toBuffer` returns different buffer types depending on platform, so this will work on Node and browser. It also either returns a reference to the backing buffer or a slice of it, so this is both fast and memory-efficient.
=> Change ProtoBuf.Builder.Message#toRaw to return bytes fields as buffers by default

cli/pbjs/sources/proto.js
I ran into this problem when trying to compile the protocol buffers in [CockroachDB](https://github.com/cockroachdb/cockroach).
It tries to include the same files multiple times and as a result fails complaining about duplicate definitions.
This patch fixes the issue by keeping track of which files have already been loaded.
=> Dedupe files when compiling with CLI

cli/pbjs/sources/proto.js
pbjs can't find files in this case:
```
A/ 
a.proto
B/
b.proto
b1.proto
C/
c.proto
````
in __a.proto__
```
import public "B/b.proto";
import public "B/b1.proto";
```
in __b.proto__
```
import public "C/c.proto";
```
Now pbjs imported all files as original google protoc
=> pbjs: add local path for proto imported files

cli/pbjs.js, package.json, tests/suite.js
Fixes #277.
The help output isn't quite *as* pretty as it was before, but it is pretty close:
```
$ ./bin/pbjs --help
_ |_ . _
|_)|_)|_)           ProtoBuf.js v4.0.0-b3 https://github.com/dcodeIO/ProtoBuf.js
|     '
CLI utility to convert between .proto and JSON syntax / to generate classes.
Usage: pbjs <filename> [options] [> outFile]
Options:
--help            Show help  [boolean]
--version         Show version number  [boolean]
--source, -s      Specifies the source format. Valid formats are:
json         Plain JSON descriptor
proto        Plain .proto descriptor
--target, -t      Specifies the target format. Valid formats are:
amd          Runtime structures as AMD module
commonjs     Runtime structures as CommonJS module
js           Runtime structures
json         Plain JSON …
```
=> Convert cli to use yargs

dist/ProtoBuf-light.js, dist/ProtoBuf.js, src/ProtoBuf/Builder.js
If the import root is overridden on Windows, .proto files would be imported multiple times because the same file would appear with slashes both ways: root/file.proto and root\file.proto
This code fixes it the same way as it is similarly resolved a couple of lines below.
I don't see a CONTRIBUTING document anywhere, so please tell me if I wasn't supposed to run the build or was supposed to write a test for the code.
=> Fixed duplicate import errors on Windows

package.json
The browser builds (webpack, browserify) shouldn't attempt to require and inline the unreachable `require('fs')`.
=> fix #225 ignore fs for browser builds

src/ProtoBuf/Builder/Message.js
test case:
```js
var ProtoBuf = require('protobufjs');
var prototext = String(function() {
/*
package bigint;
message Value {
oneof type {
int64 int64 = 1;
uint64 uint64 = 2;
}
}
*/
}).match(/\/\*([^]*)\*\//)[1];
var builder = ProtoBuf.loadProto(prototext);
var messageValue = builder.build('bigint.Value');
var value = new messageValue({
int64: ProtoBuf.ByteBuffer.Long.fromString("-192377746236123")
});
console.log('value: %j', value);
console.log('value.toRaw(): %j', value.toRaw());
```
output:
```bash
value: {"type":"int64","int64":{"low":-1866080987,"high":-44792,"unsigned":false},"uint64":null}
value.toRaw(): {"type":"int64","int64":{"low":-1866080987,"high":0,"unsigned":false},"uint64":null}
```
change:
`new ProtoBuf.Long(obj) -> ProtoBuf.Long.fromValue(obj)`
see: …
=> fixed: Message.toRaw() Conversion long integer type "high" is zero.

cli/pbjs.js
This can be helpful if pbjs is run in some case there's no way to use stdout redirect
=> add out to file support for pbjs

cli/pbjs/targets/json.js
protobuf.js's behaviour regarding default values is driven by the syntax: proto2 or proto3.  The enclosed patch makes it possible to select the syntax with the JS generator cli, by passing an extra attribute in `options`.
=> Allow to set syntax in JS cli output

src/ProtoBuf/Builder/Service.js
For my protobuf services, I'm using plain HTTP POST as RPC implementation.  The protobuf request message is sent as arraybuffer in the request body, and the response message is sent as arraybuffer in the response body.  The response body may be empty if the response message only has default values, especially with proto3.  In this case protobuf.js fails with `Error("Illegal response type received in service method...")`.  Please find enclosed a fix for this usecase.
For reference please have a look to W3C's XMLHttpRequest specification, stating clearly that the response body entity may be `null`: http://www.w3.org/TR/XMLHttpRequest/#response-entity-body
=> Coalesce to empty string when service response is empty

src/ProtoBuf/DotProto/Parser.js
This fixes a bug for multiple extension ranges if they are defined in the following way:
```protobuf
message Request
{
extensions 50 to 90;
extensions 200 to 300; 
}
```
The old implementation only uses the last extension range.
=> extend support for multiple extension ranges

src/ProtoBuf/Builder/Message.js
Switching to Object.keys and enumerating is much faster because it avoids repeated calls to hasOwnProperty, and since these are protobuf messages, they have inherited members. In my local test with a medium size proto (~30 properties with 3 or 4 sub objects), this improved perf by 6x. I'm using this in a system that needs high performance, and this is almost all of the CPU bound work my process is doing.
=> improves perf of  and cloneRaw by several times

cli/pbjs/util.js
The pbjs CLI tool is naively matching all `google/protobuf` imports, which prevents the use of other Google well-known types.  For instance, some of our messages reference items out of `google/protobuf/struct` and no matter how we specify import paths, the created builder always looks within the same folder as the referencing `proto` file for the imported google types.  This is because `util.isDescriptor(imports[i])` returns `true` for any Google imports (in `json.js` on line 67), so the file isn't resolved properly.
It's possible my own solution is a bit naive, but altering the regex does fix my problem, and it passes any tests that exist (although I'm not sure there are tests around `pbjs`).
Thanks!
=> pbjs: Util.isDescriptor should explicitly match `google/protobuf/descriptor`

dist/protobuf-light.js, dist/protobuf.js, src/ProtoBuf/Reflect/Element.js, src/ProtoBuf/Reflect/Message/Field.js, tests/suite.js
If encoding a field fails, protobuf.js throws an error like "Illegal value for [object Object]."  This updates Element to instead give the field name.
Fixes #422.
=> Better error messages

dist/protobuf-light.js, dist/protobuf.js, src/ProtoBuf/Builder/Message.js, src/ProtoBuf/Reflect/Message.js, tests/suite.js
See test case I added for example of what was failing.
It throws an error complaining the the virtual oneof field doesn't exist.
Fixed by not trying to set a virtual oneof field in the first place, when setting a property from an object.
Required creating a _oneofsByName map for efficient lookup.
=> Fix using constructor to copy a message containging oneofs

bower.json
Now the bower version matches the package version
=> updated byte buffer browser version.

examples/websocket/server.js
When I tried to run the websocket example it returned me an error because it was looking for long.min.js, ByteBuffer.min.js and Protobuf.min.js in a wrong folder.
=> update reference to js to copy for running the example

package.json
Glob library uses `minimatch` library which has a security vulnerability https://nodesecurity.io/advisories/118
Glob already updated its dependency version to a secure one. This change is to update glob dependency to that version.
All the tests are passing.
=> Update dep to glob@7.0.5 (security reasons)

dist/protobuf-light.js, dist/protobuf.js, src/ProtoBuf/Builder.js
This is required for compatibility with existing proto3 definitions. See #432
=> Make repeated fields packed by default in proto3

cli/pbjs/targets/json.js
The pbjs tool currently does not export RPC method stream information to the JSON format, however, the Builder expects it in the JSON input. This is fixed by setting `request_stream` and `response_stream` in the JSON output of pbjs.
Fixes #468
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dcodeio/protobuf.js/470)
=> pbjs: write RPC method stream info to JSON output

src/util.js
A little mistake of util.fetch method in browser.When using xhr,the old code forgot to run xhr.send() to make the request send out,and i add it now.
=> fix util.fetch method did not send the xhr.

cli/pbjs/targets/json.js
Fixed #469, allows the runtime to use proto3-specific rules (e.g. #459).
I realise v6 is the new hotness, but I need this so I can use v5 in the meantime.
=> Added syntax (proto2 vs. proto3) to json output.

src/ProtoBuf/Builder.js
path.join correctly handles edge cases, such as if the import root is `/`. In this case, path.join correctly returns the path of `/filename` instead of `//filename`.
=> Builder: Use path.join when running on Node

src/verify.js
=> Fix to generation of verify methods for bytes

src/message.js, tests/data/message.proto, tests/message.js
Fixing two issues in here:
1. When the `defaults` option was enabled, we were using `Object.keys(this)`
which ends up returning an array that includes things like `$root` and
asJSON. Instead we can use the `fields` we already have available.
2. For repeated values we were not setting the empty list default because the
length check would break earlier. We're now passing through when the
defaults option is set as well.
Added a test on this stuff as well.
=> Fix asJSON defaults option, make it work for repeated fields.

src/field.js
otherwise the options passed to `asJSON` (e.g. `{enum: String}`) don't take effect in children
=> Apply asJSON recursively

src/field.js
This seems to have caused webpack to load a Buffer shim when building for web.
=> Fix directly using Buffer instead of util.Buffer

src/util/pool/index.js
I got an error when encoding an empty message (`{}`).
When the message is empty,  the size is 0 and `slab` is null, so`slice.call(slab, offset, offset += size);` gave me
```
Uncaught TypeError: Method get TypedArray.prototype.subarray called on incompatible receiver null
```
Adding this solved the issue for me. Please correct me if I was using it all wrong. :joy:
=> Support pool usage when size = 0

src/rpc/service.js
Currently, the string "error" is passed to the callback on response decode errors (with the actual error passed where the decoded response would normally be). 
This updates the rpc service to pass the error as the first param to the callback.
=> Changes callback on failed response decode in rpc service

cli/targets/static.js, lib/tsd-jsdoc/publish.js
This PR will allow TS generated code to properly show when class members are potentially undefined.
If this is alright to merge, what is the quickest way to regenerate the tests/data files to reflect the changes?
=> Mark optional fields as possibly being undefined

src/enum.js, tests/api_enum.js
Duplicate enum IDs threw an exception, even if the `allow_alias` option was set to true. Pull request to handle this condition. Also added a test case.
=> handle allow_alias option for Enums

src/wrappers.js, tests/comp_google_protobuf_any.js
Now fromObject() can read back objects created with toObject()
containing google.protobuf.Any messages.
See issue #764.
=> Improved fromObject wrapper for google.protobuf.Any.

cli/targets/static.js
Since the proposed change in #794 worked, I adapted the generator.
After compiling my `.proto` with the modified version, I did not need to manually create a `Reader` anymore, as originally intended.
=> Fix Reader argument conversion in static module

cli/pbjs.js, cli/targets/json-module.js, cli/wrappers/amd.js, cli/wrappers/default.js, cli/wrappers/es6.js
This should fix #798 
Change affects AMD wrapper too, to be consistent.
Some modifications to AMD loader configs may be required, i.e. `protobufjs/minimal` should be mapped to correct file. Other option is to pass `dependency` argument to pbts and override default module name.
=> Use protobuf/minimal when pbjs target is static-module

src/verifier.js
I have found a little problem while using protobuf.js with react.js
I used the following proto file:
```
syntax = "proto3";
package api;
message Ping {
string data = 1;
};
message Pong {
string data = 1;
};
message Message {
oneof message {
Ping msg_ping = 1;
Pong msg_pong = 2;
};
}; 
```
with this compiler arguments:
`pbjs -t static-module -p src/api/ -o gen/api.js src/api/messages.proto`
Without the patch, the generated file contains this section:
```
Message.verify = function verify(message) {
if (typeof message !== "object" || message === null)
return "object expected";
let properties = {};
if (message.msgPing != null && message.hasOwnProperty("msgPing")) {
properties.message = 1;
let error = $root.api.Ping.verify(message.msgPing);
if (error)
return "msgPing." + error;
}
if …
```
=> fixed 'error' is not defined linter warning when using static/static-module and es6

cli/targets/json-module.js
"minimal" doesn't include `Root`, as mentioned in #828 and #856. Probably caused by #813.
=> Fixed dependency for json-module to use "light".

cli/lib/tsd-jsdoc.json
It is not necessary to provide include and exclude patterns in jsdoc config because pbts is setting files explicitly when pbts binary is called.
The excludePattern breaks everything when a path to project contains underscore.
E.g.:
```sh
$ pwd
/Users/nikita/Develop/_demo/demo-project
$ ./node_modules/protobufjs/bin/pbts ./bin/proto/all.js
import * as $protobuf from "protobufjs";
There are no input files to process
```
=> CLI: Remove exclude and include patterns from jsdoc config

cli/targets/static.js
All classes now are annotated as implementing their respective interfaces. 
Ex. when generating the TypeScript .d.ts,
```typescript
export class Message {}
```
now becomes
```typescript
export class Message implements IMessage {}
```
This PR, along with https://github.com/dcodeIO/protobuf.js/commit/ed7e2e71f5cde27c4128f4f2e3f4782cc51fbec7, should help solve #844.
=> CLI: Annotating class definitions with @implements

cli/targets/static.js
This PR changes the type definition of virtual oneof fields from a `string` type to a more restrictive string literal union of the possible field values.
Ex:
```protobuf
oneof data {
TypeA typea = 1;
TypeB typeb = 2;
}
```
is now annotated as 
```typescript
public data?: ("typea"|"typeb");
```
instead of 
```typescript
public data?: string;
```
This change prevents string comparison typos in TypeScript code. It also enables the use of exhaustive case-switch statements when handling `oneof` messages in application codebases.
Ex:
```typescript
function assertUnreachable(x: never): never {
throw new Error();
}
switch(message.data) {
case 'typea':
break;
case 'typeb':
break;
default:
assertUnreachable(message.data); 
}
```
=> Annotate virtual oneof fields as string literal unions

src/wrappers.js, tests/comp_google_protobuf_any.js
Not all languages accept just the fully qualified name as type_url. In
the official C++/C# protobuf library the type_url must at least start
with a '/', otherwise the name is not resolved.
Additionally we should be able to unpack types even if they have an
URL prefix like type.googleapis.com/full.type.name. This commit just
removes the URL prefix (similar as in other implementations I saw,
e.g. python).
=> Basic support for URL prefixes in google.protobuf.Any types.

cli/targets/proto.js
Defaults are not supported in proto3, and therefore should
not be appended to a `.proto` file when using `-t proto3`
flag for `pbjs`.
=> proto3: skip defaults

src/common.js
Providing a common wrapper for field_mask.proto
=> Adding field_mask to built-in common wrappers.

index.d.ts, src/parse.js, src/tokenize.js, tests/data/comments-alternate-parse.proto, tests/docs_comments_alternate_parse.js
If this new flag is true, the tokenizer will change the way it parses comments from the input. Instead of requiring /// or /** */ (docblock style) comments only, it will additionally accept // and /*   */ comments. It will consecutive lines of // comments into one multi-line comment.
The motivation here is that we want to parse comments in customer api descriptions which don't adhere to the docblock style.
=> Adds a new option to IParseOptions, alternateComment.

ext/descriptor/index.js
I'm working on a server that can dynamically discover and map gRPC services to HTTP using [ServerReflection](https://github.com/grpc/grpc-go/blob/master/reflection/grpc_reflection_v1alpha/reflection.proto). The ReflectionObject parsed from the descriptor returned by the reflection service is missing the service stubs.
=> Support Service in Root.fromDescriptor

src/parse.js, tests/comp_options-textformat.js
More information on the "Aggregate Syntax" here:
https://github.com/google/protobuf/issues/1148
These are accepted by the proto compiler but rarely used - I found an
example in the
[Cloud Endpoints docs](https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#google.api.HttpRule.FIELDS.string.google.api.HttpRule.rest_method_name).
Fixes #383.
=> Ignore optional commas in aggregate options

cli/pbts.js
This is required if pbts is called without node in the path. 
I ran into this issue while creating protobufjs build rules for the bazel build system.
=> Get node executable path from process.execPath

cli/pbjs.d.ts
The callback function of pbjs main should not enforce a return value.
=> remove return type requirement of pbjs callback

package.json
The [package browser field descriptor](https://github.com/defunctzombie/package-browser-field-spec) expects an entry point, rather than the bundle file path.
This change specifies an entry point for the three different libraries.
Addresses issue https://github.com/dcodeIO/protobuf.js/issues/1045
=> Fix package browser field descriptor

index.d.ts
For context: https://github.com/grpc/grpc-node/issues/425
The type definitions for PB 5/6 are not mutually compatible because of the `Message` class: one requires that the generic type parameter doesn't exist, while the other one require that it does. As a result, we cannot publish type definitions that are compatible with both.
This PR gives `Message<T>` a default value for `T` to work around that. This doesn't relate to any need other than what I described above, so if there is a better way to solve the problem, I would be open to implementing suggestions.
=> Make Message<T> have a default type param

src/namespace.js
Reserved ranges on a namespace level are exclusive in their second element: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto#L119
=> Treat second part of a reserved range as exclusive

src/parse.js, tests/data/test.proto
Fixes #1111. According to proto3 syntax defined [here](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec), an option can appear anywhere in the file. Don't break if we see an option after messages.
I also updated `tests/data/test.proto` to have a test coverage for this use case.
=> allow file-level options everywhere in the file

cli/pbts.js
`Long` is implicitly loaded as dependency. If that fails for some reason, `Long` will be undefined.
This PR makes sure that the types for `Long` are always in place.
=> fix: Import Long types

ext/descriptor/README.md
The variable `descriptor` is assigned both to the imported descriptor module, as well as the descriptor message. This renames the latter to `descriptorMsg`.
=> Fixed descriptor README code problem

.travis.yml
At a glance, it's hard to understand what versions of node.js this library is being tested against.  This makes things a tad more explicit.
=> build: be more explicit about tested versions of nodejs

ext/descriptor/index.js
The current implementation of Service.toDescriptor() does not properly return the service's method descriptors. The method iterator references the _methodsArray Array instance rather than its length. Also, the methods are returned in the 'methods' member of the returned object, instead of the 'method' member as defined by the spec. This PR corrects these two errors and produces accurate method descriptors for a given service.
=> Properly iterate and return method descriptors

src/root.js, tests/node/api_load-sync.js
In some cases when method `resolvePath` of the `Root` was overrided bundled definitions will not load correctly. This small patch fixes this behavior.
=> Bundled definitions correct loading

README.md
As mentioned in #1210 the website changed but there were two places
still referring to the old site.
=> docs: fix stale links to API documentation

src/root.js
Running `npm run build` fails at the minify step because of a `const` keyword in root.js: https://github.com/protobufjs/protobuf.js/blob/7bacfc8f34a1e096bca38a0ea38ecee089e8cdb5/src/root.js#L100
It looks like this was changed in https://github.com/protobufjs/protobuf.js/pull/1144. This line used to be: https://github.com/protobufjs/protobuf.js/blob/6fa4c3487c50f9e2647a384bf64cfb009752b6a7/src/root.js#L130
Here is the output:
```sh
> protobufjs@6.8.8 build /Users/erik/Code/protobuf.js
> gulp --gulpfile scripts/gulpfile.js
[15:28:28] Working directory changed to ~/Code/protobuf.js/scripts
[15:28:28] Using gulpfile ~/Code/protobuf.js/scripts/gulpfile.js
[15:28:28] Starting 'default'...
[15:28:28] Starting 'full'...
[15:28:28] Starting 'light'...
[15:28:28] Starting 'minimal'...
[15:28:28] …
```
=> Fix breaking build because of a minify error

src/encoder.js
This PR addresses a situation uncovered with #1232 where the encode method calls `hasOwnProperty` of an object which may not have a prototype. This situation came about when mapping an express request to a grpc call, where a `oneOf` object is a sub-message of a parent object. Using `Object.hasOwnProperty.call` appears to a safer approach which doesn't make assumptions about the underlying object's inheritance.
=> Use Object.hasOwnProperty instead of prototype method

src/index-minimal.js, src/reader.js, src/reader_buffer.js, src/writer.js, src/writer_buffer.js, tests/comp_bytes.js
Hi everyone!
This PR add support for configuring dynamically a Buffer util.
Similar to what you can do with the util.Long: https://github.com/protobufjs/protobuf.js#browserify-integration
```javascript
protobuf.util.Buffer = Buffer;
protobuf.configure();
```
There is a lot of Node.js modules that only works with the Node Buffer implementation but also we can use it in the browser thanks to the [feross/buffer](https://github.com/feross/buffer).
Many bundle tools like Webpack, Browserify and Parcel already includes a node built-in Buffer implementation and we can use it in protobufjs to encode/decode bytes in similar structures (Buffer) between Node and the browser.
=> Add support for buffer configuration.

.github/release-please.yml
This will configure the automated tagging of GitHub releases.
=> build: adds configuration file for tagging releases automatically

src/parse.js, tests/data/uncommon.proto
=> fix: properly parse empty messages in options

cli/pbjs.js
The documented and epected behaviour is that `--wrap es6` implies `---es6` but not the other way around.
Closes #1308
=> fix: Don't imply --wrap es6 from --es6 in pbjs

index.d.ts, src/parse.js, src/tokenize.js, tests/api_tokenize.js, tests/data/comments-alternate-parse.proto, tests/docs_comments.js, tests/docs_comments_alternate_parse.js
1. fix trailing comment in last line can be recognized as leading comment for current field by mistake.
2. new preferTrailingComment option in IParseOptions, user can choose the priority of trailing comments and leading commnets
3. test updated.
=> feat: better comment parse

src/util/minimal.js
The problem was introduced in #1363.
```
$ npm run make
...
ReferenceError: process is not defined
at Object.r.39.1 (evalmachine.<anonymous>:7:64076)
at t (evalmachine.<anonymous>:7:73046)
at Object.r.42.39 (evalmachine.<anonymous>:7:69283)
at t (evalmachine.<anonymous>:7:73046)
at Object.r.18.27 (evalmachine.<anonymous>:7:23855)
at t (evalmachine.<anonymous>:7:73046)
at Object.r.17.12 (evalmachine.<anonymous>:7:23036)
at t (evalmachine.<anonymous>:7:73046)
at Object.r.19.11 (evalmachine.<anonymous>:7:24055)
at t (evalmachine.<anonymous>:7:73046)
```
Let's make sure we actually have `process` before accessing it.
=> fix: do not fail if no process

src/util/minimal.js
An alternative to https://github.com/protobufjs/protobuf.js/pull/1363, attempting to fix the problem at the `util.global` level as proposed in https://github.com/protobufjs/protobuf.js/issues/1221#issuecomment-493147824.
Reverts #1363 and #1440, with the latter not being needed anymore. See also: https://github.com/protobufjs/protobuf.js/pull/1363#issuecomment-657820448
=> Fix util.global

index.d.ts, src/util/minimal.js
A follow-up to https://github.com/protobufjs/protobuf.js/pull/1441, specifically https://github.com/protobufjs/protobuf.js/pull/1441#issuecomment-658355477, that makes the node.js check a bit more forgiving in case the `global` object has been augmented.
Fixes https://github.com/protobufjs/protobuf.js/issues/1443, fixes https://github.com/protobufjs/protobuf.js/pull/1444
=> fix: make node detection a bit more forgiving

README.md
The json example was not equivalent to the .proto file. The message type should be nested in a namespace.
=> docs: fix the JSON example in README.md

src/method.js, tests/comp_options-parse.js, tests/data/options_test.proto
This PR follows #1256 and adds properly parsed options to JSON representation of methods.
Background: we need it to be able to read `google.api.http` method annotations which may include nested lists (`additional_bindings`) that the default options parsing cannot handle. #1256 introduced `parsedOptions` property that represents options as a proper (possibly nested) object but it did not go to JSON representation (which we use). Adding it there.
=> fix: make parsedOptions appear in method JSON representation

.github/release-please.yml, .github/workflows/release-submodule.yaml, .github/workflows/release.yaml
This switches us to using the GitHub action for both publishing from the top level, and from the CLI folder path.
---
Future _TODO_, this will release the top level module when there are changes only to the CLI (_we will probably want to add exclude logic to the top level release job, which excludes any commits that touch the `cli/` path_).
=> build: use action for publishing

src/converter.js, tests/api_converters.js, tests/data/convert.js, tests/data/test.js
closes #1500
fixes #885
The fix is from @jawid-h in #1500. Thanks to him.
I added tests.
Note the change in behavior:
```typescript
-                test.same(obj.bytesVal, [], "should set bytesVal");
+                test.same(obj.bytesVal, protobuf.util.newBuffer(0), "should set bytesVal");
```
The default value for an empty `Buffer` is now a Buffer of length 0 vs an empty array before.
I have not included the generated files in this CL (`dist/*` and `index.d.ts`).
Please let me know if they should be there and I'll add them.
=> fix!: encoding of empty Buffers

cli/targets/static.js, package.json, tests/cli.js, tests/data/cli/test.proto
Fixes #1596.
The problem happens when an instance of a statically generated class (e.g. generated with `pbjs`) is passed to a dynamically generated `.fromObject` (e.g. from a protobuf `Root` loaded in the runtime). Since the statically generated instance has all non-optional fields set to their default values in the prototype, including the `oneof` fields, the resulting message is incorrect because it has all non-primitive members of `oneof` assigned to the default value (e.g. empty string), which make serialized object deserialize incorrectly by official protobuf implementations (e.g. Python). The implementation of dynamic `.fromObject` has a safety check that does nothing if the `typeof` shows it's already an object of the correct type, but this safety check does not work since they …
=> fix: fromObject should not initialize oneof members

src/namespace.js
In parse.js line 391, case rule === "proto3_optional" will do "parent.add(oneof)". But namespace.js not compatible this type.
=> fix: parse.js "parent.add(oneof)“ error

src/roots.js
=> docs: fix typo in roots.js

src/tokenize.js, tests/api_tokenize.js, tests/data/comments-alternate-parse.proto, tests/data/comments.proto, tests/docs_comments.js, tests/docs_comments_alternate_parse.js
There is an issue with preferred trailing comment processing (preferTrailingComment = true), if the next field contains a leading comment.
```
message A {
// Field with both comments
string field1 = 1; // trailing comment
 
// Field with leading comment
string field2 = 2;
}
```
**Actual Result**:
field1.comment = "Field with both comments"
field2.comment = "field2 trailing comment"
**Expected Result**:
field1.comment = "field1 trailing comment"
field2.comment = "field2 trailing comment"
=> fix: invalid processing of leading and trailing comments

cli/pbjs.js, cli/targets/static.js, tests/cli.js, tests/data/cli/null-defaults.proto
Discussed in #1572 : add an option to pbjs to allow default values of fields to be null instead of the zero value for the type (0 for number, "" for strings)
=> feat: add null-defaults option

package-lock.json, package.json
Bump `eslint` dependency. `eslint` 8.x will force `minimatch` 3.1.2 which allows to avoid using the older version with a reported [vulnerability](https://snyk.io/vuln/npm:minimatch) (of course, it's just a transitive devDependency, but still being reported as a problem here and there).
=> fix(deps): update eslint to ^8.15.0

.github/workflows/test.yml
Our release PRs don't have tests run, because they're opened by an action themselves.
This will allow us to add a `ci` label to kick off tests.
=> build: run tests if ci label added

src/field.js, tests/comp_optional.js
https://github.com/protobufjs/protobuf.js/pull/1584 made proto3 optional
scalars default to null when using static/static-module, but the old
behaviour remained when using reflection (eg json-module). This PR
attempts to make the latter case behave the same way (would love to use
static code generation, but the resulting file sizes are too large).
This passes the existing tests, but I do not know the codebase well, so I
am not sure if this is the best approach or not.
=> fix: proto3 optional scalars should default to null in reflection API

cli/pbjs.js
This PR adds the "--alt-comment" CLI option which sets the already existing "alternateCommentMode" parse option.
=> feat: add alt-comment CLI option

src/namespace.js, tests/api_oneof.js
`object must be a valid nested object`
=> fix: extensions broke oneof

src/parse.js, tests/data/test.json, tests/data/test.proto
This fixes support for proto files that have nested messages or enums declared within groups, like this:
```proto
syntax = "proto2";
message Foo {
repeated group Field = 1 {
message Bar {
optional bool my_bool = 2;
}
optional string my_string = 3;
optional Bar my_bar = 4;
}
}
```
=> fix: support for nested messages and enums within group blocks

src/converter.js, tests/api_converters.js
In official protobuf implementations unknown numeric enum values are accepted and not discarded. Changing the behavior of `fromObject` to store unknown enum values. `toObject` will also dump them as is (without converting to a string, because it does not know the string representation for an unknown enum value).
I'm not changing `verify` which still won't accept unknown values.
Since the changes in the code generators are hard to read, here are some examples.
Imagine this proto:
```proto
syntax = "proto3";
enum E {
DEFAULT = 0;
KNOWN = 1;
}
message M {
E a = 1;
repeated E b = 2;
}
```
This is the diff in the generated code for `fromObject` and `toObject`, explanations are below.
```diff
--- original.js	2022-08-26 16:51:09.932392333 +0000
+++ changed.js	2022-08-26 17:23:27.797270346 +0000 …
```
=> feat: accept unknown enum values in fromObject

src/converter.js, tests/cli.js, tests/data/cli/test.proto
Having an aliased default value in an enum now breaks the generated JS static code:
```
SyntaxError: Multiple default clauses
at Espree.raise (/Users/fenster/repos/nodejs-appengine-admin/node_modules/protobufjs-cli/node_modules/espree/dist/espree.cjs:675:25)
at Espree.raiseRecoverable (/Users/fenster/repos/nodejs-appengine-admin/node_modules/protobufjs-cli/node_modules/espree/dist/espree.cjs:691:18)
at Espree.pp$8.parseSwitchStatement (/Users/fenster/repos/nodejs-appengine-admin/node_modules/protobufjs-cli/node_modules/acorn/dist/acorn.js:1107:34)
at Espree.pp$8.parseStatement (/Users/fenster/repos/nodejs-appengine-admin/node_modules/protobufjs-cli/node_modules/acorn/dist/acorn.js:909:39)
at Espree.pp$8.parseBlock (/Users/fenster/repos/nodejs-appengine-admin/node_modules/protobufjs-cli/nod …
```
=> fix: generate valid js code for aliased enum values

README.md
=> docs: update CDN (dist folder removed from source control)

index.d.ts, src/namespace.js
Fixing the type declaration to allow one very special case: a field extension that is a proto3 `optional` field. Internally, proto3 `optional` fields are represented as a single field `oneof`s, which makes it the first case ever when a `oneof` can be a `nested` object.
Example: [bigquery-storage](https://github.com/googleapis/googleapis/blob/fafd03f8da224663da0d83ee7c6ed1d84f3cb2e6/google/cloud/bigquery/storage/v1/annotations.proto#L14-L28)
```proto
extend google.protobuf.FieldOptions {
optional string column_name = 454943157;
}
```
Related part of the JSON:
```json
"nested": {
"_columnName": {
"oneof": [       <--- this is not accepted without the fix
"columnName"
]
},
"columnName": {
"type": "string",
"id": 454943157,
"extend": "google.protobuf.FieldOptions",
"options": { …
```
=> fix(types): nested object can be a oneof

src/root.js
=> fix: 🐛 error should be thrown

cli/package-lock.json, cli/pbjs.js, cli/test.json, cli/util.js, package.json, tests/cli.js, tests/data/cli/filter.json, tests/data/cli/test-filter-import.proto, tests/data/cli/test-filter.proto
I encountered a problem in the project I was working on: Due to the large size of my project and the complexity of the proto, the resulting js static code file was very large, nearly 100,000 lines before uncompression, about 5mb, and nearly 1mb even after compression , which causes my pages to load slower.
Later I found out the cause of the problem: my page only uses a few messages, but I still need to compile the entire file and all the messages, enums, etc. of all dependent files, and there is a huge waste here.
Finally, I found a solution: by adding a filter parameter to the cli, to filter those structures that we don't need at all, so that our files are greatly reduced, which will be very useful in a huge project. Eventually I cut it from 100,000 lines to 10,000.
example：
pbjs …
=> feat(cli): generate static files at the granularity of proto messages

src/root.js
Reverts protobufjs/protobuf.js#1817
Cc: @binsee 
This breaks the well established logic of proto loading (see #1863, I also see the problem in `google-gax` package). I _suspect_ that the places that got broken are actually incorrect, but we cannot just break things like that even if we are making them work properly. So rolling back for now, we'll need to figure out the safer way of fixing the original problem.
=> fix: Revert "fix: 🐛 error should be thrown"

src/util/minimal.js
This solves the compilation errors when importing protobuf.js in duktape Javscript engine.
Issues: https://github.com/protobufjs/protobuf.js/issues/1829
=> fix: use ES5 style function syntax

cli/pbjs.js, src/root.js
Upgrading from 6.7 to 7.0, we ran into the following issue, using the CLI: If the `.proto` files given as arguments contain some `google/protobuf/*.proto` files, as well as `import` statements importing them in other files, the CLI command terminates with error "duplicate name '..' in Namespace .google.protobuf". Basically it didn't recognize that a common file had already been fetched and parsed. Interestingly this only happened if we used the absolute paths of the `.proto` files.
We found that enforcing the use of the bundled filename in the `fetch` function fixes the issue, and this PR does just that. In an older version the bundled filename was used here, but it was dropped in [this commit](https://github.com/protobufjs/protobuf.js/commit/15ee83ffa6cfd755ea04208110ddb5003adf98b1). …
=> fix: use bundled filename to fix common pb includes

cli/pbjs.js
Upgrading from 6.7 to 7.0 we encountered a possible bug in resolving the paths to the included Google protobuf files. With the older version, when the CLI was bundled in the same library, on line 81 of `cli/pbjs.js`, `__dirname` was `[..]/node_modules/protobufjs/cli`, so `path.join(__dirname, "..")` evaluated to `[..]/node_modules/protobufjs`, but now `__dirname` is `[..]/node_modules/protobufjs-cli`, so `path.join(__dirname, "..")` is just `[..]/node_modules`, and later, on lines 198--200, protobuf files are searched from a non-existing folder, for example `[..]/node_modules/google/protobuf/descriptor.proto`.
This PR inserts the missing `protobufjs` directory to the search path.
=> fix(cli): fix relative path to Google pb files

src/parse.js, tests/comp_whitespace-in-type.js, tests/data/whitespace-in-type.proto
Some proto packages are pretty long, and some proto formatters might split them into multiple lines in a weird way, like here:
https://github.com/googleapis/googleapis/blob/master/google/ads/googleads/v13/common/asset_set_types.proto#L176-L177
```
google.ads.googleads.v13.enums.LocationStringFilterTypeEnum
.LocationStringFilterType filter_type = 2;
```
The parser expects the whole type name to be just one token, and fails to parse this. I'm fixing the parser to accept multiple tokens as the type name: keep glueing tokens together while there are periods that separate parts of the type name.
=> fix: type names can be split into multiple tokens

src/util.js, tests/api_util.js
Follow up to #1731, fixes a bug introduced in #1256.
=> fix: do not let setProperty change the prototype

bench/prof.js, cli/lib/tsd-jsdoc/publish.js, src/converter.js, src/parse.js, tests/cli.js, tests/comp_options-parse.js
The `while` loop in `parseOptionValue` can be infinite if the closing brace `}` it expects never comes.
```
const protobuf = require('protobufjs');
protobuf.parse("option (foo).whatever = {");
```
Reported by @oetr.
Minor unrelated changes also in this PR, because I'm too lazy to create a separate one:
- changed `eslint-disable-line` to a proper `eslint-disable-next-line` in a few places to fix linting errors;
- removed extra logging in one of the tests.
=> fix: possible infinite loop when parsing option

src/tokenize.js, tests/data/comments-alternate-parse.proto, tests/docs_comments_alternate_parse.js
This fixes a crash in parsing sequences of comments like the following:
```
//
/*
*/
```
The conditions to trigger the crash are:
1. alternateCommentMode is set to true
2. A single line comment is immediately followed by a block comment
3. The block comment spans at least two lines
The crash happens because `isDoubleSlashCommentLine` returns true for lines starting with `/*`. It only checks for one slash because in the first callsite, `offset` points to the second slash character and the character before it is guaranteed to also be a slash. But this is not true in the second callsite. The result is that it treats the line with `/*` as a single line comment.
=> Fix crash in comment parsing (fixes #1616)

src/reader.js
Used `Buffer.alloc` if it's available.
#1411
=> Fixed deprecation warning for new Buffer

src/root.js, tests/api_root.js, tests/data/badimport.proto
Fixes #1954.
The `finish` function can be called in two modes, sync (when it throws an exception), or async (when it calls the callback). It makes sure the callback won't be called twice, but it makes one extra step and clean up the callback even it was called in sync mode. It causes problems such as in #1954 where instead of reporting "file not found" when parsing a proto, it jumps over that error and only reports the next error–or no error if the parsing happens to succeed without a bunch of imports being skipped as a result of the first exception.
Let's avoid clearing the callback if we haven't used it yet.
The problem actually occurs when loading a proto file in sync mode (e.g. by running `root.loadSync(filename)`, which is what `pbjs` does), hence the PR title.
=> fix: report missing import properly in loadSync

src/parse.js, tests/data/google/protobuf/descriptor.proto, tests/data/uncommon.proto
Extension declarations were released in v23.0 of protobuf
=> feat: add handling for extension range options

index.d.ts, src/type.js
This is causing downstream problems with some recent descriptor.proto changes that add reserved names.
=> fix(types): reserved field in IType can contain reserved names

README.md
Update to correct command for building typescript definitions tp `npm run build:types`
=> Docs: Update readme to correct command for creating types

cli/lib/tsd-jsdoc/publish.js
Multi-line typedefs now generates valid type syntax
Fixes #2009
=> fix: multi-line typedefs generating "let" statements

lib/inquire/index.js
AS POST TITLE.
I think this can be published as an alpha version for more tests.
=> fix: remove eval usage so that chrome extension MV3 can run properly

cli/targets/proto.js, cli/targets/static.js, index.d.ts, src/decoder.js, src/encoder.js, src/enum.js, src/field.js, src/index-light.js, src/namespace.js, src/object.js, src/oneof.js, src/parse.js, src/root.js, src/service.js, src/type.js, src/util.js, tests/api_enum.js, tests/api_field.js, tests/api_root.js, tests/api_service.js, tests/api_type.js, tests/cli.js, tests/comp_google_protobuf_any.js, tests/comp_groups.js, tests/comp_packed-repeated.js, tests/data/cli/null-defaults-edition2023.proto, tests/data/uncommon.proto, tests/feature_grammar.js, tests/feature_resolution_editions.js, tests/other_protocolerror.js
Protobuf.js was audited for the following features:
*  Field presence - Full support of all 3 presence modes, although the behavior appears to be non-conformant in general.  The feature values were hooked up to the existing behaviors, with new tests added for edition 2023.
* Packed encoding - Both packed and expanded encoding are supported and conformant.  Some opportunistic cleanup was done, but was behavior-preserving.
* Delimited encoding - Proto2 groups are supported but mark a property on the *message* rather than the field.  This information was moved to the field and the more general delimited logic was added (with tests).
* Enum type - All enums are open, this was left untouched.  CLOSED enum_type will be ignored in edition 2023 (which is consistent with our long-term goal …
=> feat: add Edition 2023 Support

index.d.ts, src/namespace.js, src/object.js, src/root.js, src/service.js, src/type.js
Now that resolveAll has been optimized, go back to ensuring that it's been called on every load.  This is necessary to guarantee correctness of feature helpers, not just for feature resolution.  Caching should make duplicate calls extremely cheap.
Just to be safe, this also does a second round of optimizations to lookup.  For a large test proto, the time to run `resolveAll` has been cut in half, in addition to the ~30x wins from the previous PR.  This also increases caching a bit to reduce costs of noop `resolveAll` calls, using the same namespace-based caching strategy as for feature resolution
=> fix: ensure that types are always resolved

ext/descriptor/index.js, google/protobuf/descriptor.json, google/protobuf/descriptor.proto, src/namespace.js, src/root.js, tests/comp_import_extend.js, tests/comp_parse-uncommon.js, tests/data/google/protobuf/descriptor.proto, tests/data/invalid-lookup.proto
This extension had virtually no test coverage and was already fairly buggy in proto2/proto3.  The addition of editions support broke it completely though, notably https://github.com/protobufjs/protobuf.js/pull/2068 which added some caching that doesn't work in the case of root-less types.
This PR adds some basic test coverage, and cleans up the code to work more smoothly under editions.  It is still not safe to use it in the following cases, where it will produce bad results:
* Converting descriptors from one syntax/edition to another
* Loading partial editions descriptors (e.g. calling fromDescriptor on anything but a Root node)
Fixes https://github.com/protobufjs/protobuf.js/issues/2072
=> fix: descriptor extensions handling post-editions

google/protobuf/descriptor.json, google/protobuf/descriptor.proto
A recent change (#2075) edited descriptor.proto to include a `reserved` statement that combines a field number and field name in the same line. This is specifically called out in the proto language guide as invalid.
https://protobuf.dev/programming-guides/editions/#reserved
> Note that you can’t mix field names and numeric values in the same
> `reserved` statement.
Protobuf.js itself seems to handle this syntax just fine, but other tools like protoc will choke on it.
=> fix: invalid syntax in descriptor.proto
